apiVersion: apps/v1
kind: Deployment
metadata:
  name: modularis
  labels:
    io.kompose.service: modularis
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 2
        maxUnavailable: 0
  selector:
    matchLabels:
      io.kompose.service: modularis
  template:
    metadata:
      labels:
        io.kompose.service: modularis
    spec:
      volumes:
      - name: idfk
        secret:
          secretName: discord-token
      containers:
      - name: modularis
        image: eiachh/modularis
        imagePullPolicy: "Never"
        env:
        - name: "ASPNETCORE_URLS"
          value: "http://localhost:5000"
        ports:
        - containerPort: 5003
        volumeMounts:
        - name: idfk
          readOnly: true
          mountPath: "/app/ProjectModularisBot/config"